/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x90, 0x9F, 0xE4, 0xDE, 0xEC, 0x4B, 0xD9, 0xA3}
#define VIAL_UNLOCK_COMBO_ROWS { 5 }
#define VIAL_UNLOCK_COMBO_COLS { 6 }

#define DYNAMIC_KEYMAP_MACRO_COUNT 100
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define VIAL_TAP_DANCE_ENTRIES 75

#define ONESHOT_TIMEOUT 20000 
#define VIAL_COMBO_ENTRIES 1
#define VIAL_KEY_OVERRIDE_ENTRIES 1

//#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 96 // 64 too low, 128 too high

#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_RIVERFLOW
